import { getRandomInt } from "@/utils/randoms";

const adjectives = [
  "celestial",
  "astral",
  "fearless",
  "fierce",
  "fresh",
  "funky",
  "glowing",
  "keen",
  "lit",
  "nifty",
  "playful",
  "primal",
  "quick",
  "quiet",
  "savage",
  "slick",
  "solid",
  "spunky",
  "stellar",
  "stoked",
  "trendy",
  "vibrant",
  "wise",
  "zesty",
  "zippy",
  "bold",
  "brisk",
  "calm",
  "cool",
  "crisp",
  "daring",
  "deft",
  "driven",
  "dapper",
  "eager",
  "fiery",
  "fluent",
  "fresh",
  "gentle",
  "gutsy",
  "hushed",
  "jazzy",
  "keen",
  "lively",
  "luminous",
  "mellow",
  "mighty",
  "nimble",
  "noble",
  "plucky",
  "proud",
  "pure",
  "quick",
  "quiet",
  "rapid",
  "rare",
  "sly",
  "spry",
  "stellar",
  "swift",
  "tense",
  "tidy",
  "true",
  "vigilant",
  "witty",
  "zany",
  "luminous",
  "spiritbound",
  "starborn",
  "cosmic",
  "ethereal",

  "infinite",
  "blessed",
  "silent",
  "still",
  "peaceful",
  "gentle",
  "pure",
  "inner",
  "tranquil",
  "guided",
  "magnetic",
  "earthborn",
  "slick",
  "bold",
  "brave",
  "electric",
  "vivid",
  "sharp",
  "fresh",
  "wild",
  "neon",
  "swift",
  "chill",
  "clever",
  "stealthy",
  "smooth",
  "epic",
  "rad",
  "loud",
  "bright",
  "snappy",
  "hyper",
  "ascended",

  "ethereal",
  "sacred",
  "tranquil",
  "luminous",
  "infinite",
  "mystic",
  "divine",
  "silent",
  "celestial",
  "serene",
  "awakened",
  "harmonic",
];

const nouns = [
  "Light",
  "Starlight",
  "pulse",
  "zenith",
  "wave",
  "spark",
  "echo",
  "flash",
  "flare",
  "storm",
  "rider",
  "hunter",
  "striker",
  "wizard",
  "ninja",
  "raven",
  "phoenix",
  "viper",
  "glide",
  "quake",
  "sparkle",
  "ember",
  "twist",
  "flare",
  "blade",
  "rift",
  "spark",
  "charge",
  "quake",
  "flare",
  "storm",
  "ghost",
  "fury",
  "glow",
  "hover",
  "ignite",
  "jet",
  "knight",
  "leap",
  "muse",
  "nova",
  "orbit",
  "pulse",
  "quest",
  "rage",
  "rush",
  "scout",
  "shift",
  "slash",
  "smoke",
  "sniper",
  "spark",
  "spirit",
  "strike",
  "thunder",
  "trick",
  "vibe",
  "whisper",
  "zephyr",
  "zest",
  "bolt",
  "crash",
  "dash",
  "Galaxy",
  "Maverick",
  "Falcon",
  "Rocket",
  "Pixel",
  "Blaze",
  "Phantom",
  "Nova",
  "Shadow",
  "Rebel",
  "Rebellion",
  "Cipher",
  "Jinx",
  "Glitch",
  "Vortex",
  "Surge",
  "Ghost",
  "Turbo",
  "Dragon",
  "Pulse",
  "Zenith",
  "Wave",
  "Dreamdust",
  "Bliss",
  "voidwalker",
  "lightweaver",
  "Adventurer",
  "Innerverse",
  "Oneness",
  "SacredCore",
  "HigherSelf",
  "Nirvalight",
  "Stillness",
  "Flowstate",
  "Harmony",
  "Balance",
  "Breathlight",
  "Soulrest",
  "Zenith",
  "Quietude",
  "Oracle",
  "Seer",
  "Visionary",
  "Myst",
  "Arcana",
  "Rune",
  "Aura",
  "ThirdEye",
  "Soulcaster",
  "Clairlight",
  "Whisperveil",
  "Moonleaf",
  "Sunroot",
  "Serenity",
  "Nebula",
  "Seeker",
  "Awakening",
  "Voyager",
  "Whisper",
  "Falcon",
  "Moon",
  "Solstice",
  "Windcaller",
  "Forestlight",
  "Skybloom",
  "Starpetal",
  "Tidewhisper",
  "Dawnseed",
  "Emberfall",
  "Rainchant",
  "Aura",
  "Soul",
  "Lightpath",
  "Soulrise",
  "Spiritwave",
  "Enlight",
  "Path",
  "Wanderer",
  "Echo",
  "Bloom",
  "Sky",
  "Spirit",
  "Owl",
];

function getRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function generateSpiritualUsername(): string {
  const adjective = getRandom(adjectives);
  const noun = getRandom(nouns);
  return `${adjective}${noun}`;
}

function generateSpiritualName(): string {
  const adjective = getRandom(adjectives);
  const noun = getRandom(nouns);
  return `${adjective} ${noun}`;
}

const spiritualBiograms = [
  "Professional overthinker",
  "Powered by coffee and good vibes",
  "Living life one pixel at a time 🖥️✨",
  "Fueled by passion and caffeine ☕🔥",
  "Just exploring the universe 🚀",
  "Building the future 👷‍♀️⚙️",
  "Chasing sunsets and deadlines 🌅⏳",
  "Breaking boundaries 💥",
  "Curating those vibes 💆",
  "Making magic with a keyboard 🪄⌨️",
  "Powered by curiosity and kindness 🧠💖",
  "Less perfection, more progress 📈💪",
  "Always learning, always growing 📚🌱",
  "Pixel pusher and soul seeker 🖼️🔮",
  "Designing my own universe 🎨🌌",
  "I put the ‘pro’ in procrastinate",
  "Here for the memes and the meaning",
  "Seeker of light and truth",
  "Dreaming in pixels and moonlight",
  "Coding by day, stargazing by night",
  "Floating through this dimension with purpose",
  "Soul wrapped in a hoodie, mind in the clouds",
  "Running on intuition and iced coffee",
  "Here to vibe, build, and fly ✈️",
  "Soft soul, sharp mind, wild heart",
  "Just a spark in the cosmic soup",
  "Channeling good energy & clean code",
  "Part-time wanderer, full-time dreamer",
  "Infinite ideas, limited time",
  "Living softly with fierce ambition",
  "Built from stardust and HTML",
  "In a committed relationship with the sky",
  "Designing moments, not just interfaces",
  "Frontend dev on a spiritual side quest",
  "Typing spells into code editors",
  "Mystic by nature, dev by trade",
  "Craving peace and push requests",
  "Your local cloud surfer ☁️",
  "Walking the path of inner peace",
  "Grounded soul with cosmic dreams",
  "Living in harmony with the universe",
  "Guided by intuition and love",
  "Here to raise the vibration",
  "Channeling light through code and soul",
  "Breathing in calm, exhaling clarity",
  "Rooted in stillness, reaching for stars",
  "Energy in motion, spirit in flow",
  "Dreaming with open eyes and a full heart",
  "Wandering through wonder and wisdom",
  "Creating from stillness and stardust",
  "On a journey inward to expand outward",
  "Dancing between realities with grace",
  "Heart open, spirit grounded",
  "Infinite soul on a sacred path",
  "Echo of ancient wisdom in modern form",
  "Softly glowing in a noisy world",
  "Translating silence into beauty",
];

function generateSpiritualBio(): string {
  const bio = getRandom(spiritualBiograms);
  return `${bio}`;
}

const spiritualTypes = [
  "Visionary",
  "Game developer",
  "Game designer",
  "Designer",
  "Spiritual guide",
  "Artist",
  "Musician",
  "Engineer",
  "Teacher",
  "Content creator",
  "3D artist",
  "CEO",
  "Songwriter",
  "Dancer",
  "Creative director",
  "Creator",
];

function generateSpiritualType(): string {
  const type = getRandom(spiritualTypes);
  return `${type}`;
}

export const newProfileTemplate = {
  username: generateSpiritualUsername(),
  name: "My Name",
  posts: getRandomInt(20, 300),
  followers: getRandomInt(3000, 800000),
  following: getRandomInt(10, 1000),
  bio: generateSpiritualBio(),
  links: "click.me",
  type: generateSpiritualType(),
  avatar: null,
};
