//layout always a server component
import "./globals.css";

import type { Metadata } from "next";

import { librebaskerville, nunito } from "@/components/layout/fonts";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { ThemeManager } from "@/utils/ThemeManager";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${librebaskerville.variable} ${nunito.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
        try {
          if (localStorage.getItem("theme")?.includes("dark") || (localStorage.getItem("theme") === null && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark')
          } else {
          document.documentElement.classList.remove('dark')
          }
        } catch (_) {}
          `,
          }}
        />
        <ThemeManager />
        <Header />
        <main className="min-h-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
