import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Particle from "@/components/layout/Particle";
import MouseLight from "@/components/layout/MouseLight";
import Footer from "@/components/layout/Footer";
import { randomize } from "@/lib/randomize";
import Header from "@/components/layout/Header";
import { ThemeManager } from "@/lib/ThemeManager";

const currentPalette = ["#02f0df", "#ff7100"];

// if  localStorage.theme === themesData type===dark ||
// (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches) set theme to seeker, if not set to indigoChild
// set class to string type+name

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeManager />
        <Header />
        <main className="pt-22">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
