import "./globals.css";

import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import { librebaskerville, nunito } from "@/components/layout/fonts";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { themesData } from "@/constants/themes";
import { ThemeManager } from "@/utils/ThemeManager";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const themes = themesData.map((theme) => theme.key);

  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${librebaskerville.variable} ${nunito.variable} antialiased`}
      >
        <ThemeProvider enableSystem={true} attribute="class" themes={themes}>
          <ThemeManager />
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
